### ISSUE TITLE
Feature Request - show source directly on github without forcing dmg download

### ISSUE THREAD

**Issue by will-riley** [henri/installpkg#6]
Where's the source? Just a bunch of installers. Sorta suspicious looking at first glance. Forcing people to unpack and dig into a dmg to see the source is...hmm. An extra step that usually isn't there. Running an installer with root privs to bring in a bash script and man file is very "Average Mac User Compatible", but it would be great to be able to look at it directly in github so the user knows what's going on straight away. Thanks for posting this though, clearly took some effort to put it together! Bravo

**Comment by henri** [comment]
Glad you like installpkg. The source code and even the source code to the build the package is all available on github : https://github.com/henri/installpkg

If you would like to see the primary script which kind of makes it all tick take a look at : https://github.com/henri/installpkg/blob/master/install_components/installpkg

its all there as mentioned even the build script (requires luggage). Nothing dodgy. Used by loads of places :) - + check it out for yourself. If you want a script to build it so that you can code sign, then let me know. I am sure it would not be that tricky to update. The entire system was developed and built way before that existed and I have not had any requests to add that option. Although, I can see it could be useful for some instances. Normally, people will use installpkg within a package - kind of like the old meta package formats to install extra bits.

You are likely just clicking on the download link for the latest version which is compelled and built into a package. This is able to be used to update installpkg using installpkg. 

installpkg -iuh http://lucid.systems/download/installpkg

Finally, as someone into sound you may (or may not) like to check out some live recordings of electronic performances : http://www.htrax.xyz
